# Generated by Django 3.2.18 on 2023-03-09 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Siteuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_organizer', models.BooleanField(default=False)),
                ('site_owner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, unique=True)),
                ('event_date', models.DateTimeField()),
                ('event_date_reg_close', models.DateTimeField()),
                ('event_location', models.CharField(max_length=100)),
                ('event_location_url', models.URLField()),
                ('number_cars', models.IntegerField(default=1)),
                ('feature_cars', models.BooleanField(default=False)),
                ('number_feature_cars', models.IntegerField(default=0)),
                ('event_description', models.TextField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20, unique=True)),
                ('car_year', models.IntegerField()),
                ('car_make', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=50)),
                ('car_origin', models.CharField(max_length=10)),
                ('car_modifications', models.CharField(max_length=200)),
                ('feature_consideration', models.BooleanField(default=False)),
                ('feature_approved', models.BooleanField(default=False)),
                ('car_event', models.CharField(default='No Event Specified', max_length=50)),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
