# Generated by Django 3.2.18 on 2023-04-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpapp', '0003_auto_20230318_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
